### ISSUE TITLE
ONLY TURNS ON AND OFF GLOBE INSIDE LIGHT

### ISSUE THREAD

**Issue by BENJAMINZSIMON** [rylee-s/Homebridge-Litter-Robot-4#1]
Hi there,

This went into HomeKit just fine however all it does in HomeKit is turns on or off the interior light.... shouldn't it do something else like say litter level etc?
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by rylee-s** [comment]
Thanks for the issue @BENJAMINZSIMON 

This project is still new and I am working on getting a roadmap together. 

Currently the only functionality is toggling the globe light on and off. I will make sure Litter Levels get into the next update. I am also planning on adding cycle status, cycle command, globe light brightness, and the subscription to async updates for things like waste drawer being full and stuck globe.

**Comment by BENJAMINZSIMON** [comment]
Thanks for the update! That's amazing to hear! Can't wait to see those updates :)

**Comment by eknofsky** [comment]
@rylee-s is this something you're actively working on? If this is low prio in your time I'm going to fork and work on this separate

**Comment by rylee-s** [comment]
@eknofsky I'm actively working on it. I'm new to homekit so I am trying to get familiar with the configurations. Hoping to have something up this week along with some tests.
