### ISSUE TITLE
Drawer Full Sensor

### ISSUE THREAD

**Issue by scottg1965** [rylee-s/Homebridge-Litter-Robot-4#2]
**Is your feature request related to a problem? Please describe:**
No

**Describe the solution you'd like:**
Sensor for Draw Full events so that I can turn a light on.

**Describe alternatives you've considered:**
IFTTT works but is not a HomeKit solution.

**Comment by rylee-s** [comment]
🫡 Taking a look now.

**Comment by rylee-s** [comment]
I added a new Humidity Sensor to represent the drawer level. Looks like whisker uses 110% as the "full won't cycle" value so setting an automation to trigger when the 'humidity level' is greater than 95% should indicate when the drawer is actually full. (should)

If you update to the newest version from the plugin's page you should be ready to rool. Thanks for the ticket! Let me know if you have any issues.

**Comment by scottg1965** [comment]
Thank you. I can confirm it works On Feb 16, 2024, at 4:14 AM, Rylee ***@***.***> wrote:﻿
Closed #2 as completed.
